# Generated by Django 6.0.5 on 2026-06-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_phone_number',
            field=models.CharField(blank=True, null=True, verbose_name='کد فعالسازی شماره'),
        ),
    ]
