# Generated by Django 6.0.5 on 2026-06-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_alter_user_active_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='شماره همراه'),
        ),
    ]
