# Generated by Django 5.2.15 on 2026-07-06 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0009_rename_iranian_cit_code_1c3b38_idx_sage_city_code_8db749_idx_and_more'),
        ('user_module', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=200, verbose_name='محله / شهرک')),
                ('street', models.CharField(max_length=200, verbose_name='خیابان / کوچه')),
                ('building', models.CharField(blank=True, max_length=200, null=True, verbose_name='ساختمان')),
                ('number_plate', models.IntegerField(verbose_name='شماره پلاک')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iranian_cities.county', verbose_name='شهرستان')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iranian_cities.province', verbose_name='استان')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
    ]
