# Generated by Django 5.2.15 on 2026-07-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_alter_user_id_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='full_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس کامل'),
        ),
    ]
