# Generated by Django 6.0.5 on 2026-07-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='تلفن'),
        ),
    ]
