# Generated by Django 6.0.5 on 2026-06-23 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='عنوان در url')),
                ('image', models.ImageField(upload_to='articles', verbose_name='تصویر')),
                ('excerpt', models.TextField(verbose_name='گزیده')),
                ('meta_description', models.CharField(max_length=500, verbose_name='توضیحات متا')),
                ('content', models.TextField()),
                ('reading_time', models.PositiveIntegerField(default=0, verbose_name='زمان مطالعه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
