# Generated by Django 6.0.5 on 2026-06-24 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_module', '0002_alter_articlemodel_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles_module.articlemodel', verbose_name='مقاله')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تعداد بازدید',
                'verbose_name_plural': 'تعداد بازدید ها',
            },
        ),
    ]
