# Generated by Django 6.0.5 on 2026-06-28 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_module', '0005_articlecomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles_module.articlecomments', verbose_name='والد'),
        ),
    ]
