# Generated by Django 6.0.5 on 2026-06-28 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_module', '0006_articlecomments_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
