# Generated by Django 6.0.5 on 2026-06-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_module', '0007_articlecomments_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='number_of_like',
            field=models.IntegerField(default=0, verbose_name='تعداد لایک'),
        ),
    ]
