# Generated by Django 6.0.5 on 2026-06-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_module', '0009_remove_articlecomments_number_of_like_commentlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200, verbose_name='تگ')),
                ('in_url', models.SlugField(max_length=200, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'تگ مقاله',
                'verbose_name_plural': 'تک های مقاله',
            },
        ),
    ]
