# Generated by Django 6.0.5 on 2026-07-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_module', '0010_articletags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='tag',
            field=models.ManyToManyField(blank=True, to='articles_module.articletags', verbose_name='تگ ها'),
        ),
    ]
