# Generated by Django 6.0.5 on 2026-07-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_module', '0011_articlemodel_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletags',
            options={'verbose_name': 'تگ مقاله', 'verbose_name_plural': 'تگ های مقاله'},
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='url_title',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=100, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='articletags',
            name='in_url',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=200, verbose_name='عنوان در url'),
        ),
    ]
