# Generated by Django 6.0.5 on 2026-06-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام برند')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products_module.productcategory', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی محصولات',
                'verbose_name_plural': 'دسته بندی های محصولات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='تصویر')),
                ('short_description', models.CharField(max_length=400, verbose_name='توضیحات کوتاه')),
                ('descriptions', models.TextField(verbose_name='توضیحات')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود / غیر موجود')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_module.productbrand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_module.productcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
