# Generated by Django 6.0.5 on 2026-07-03 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0004_likecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ویژگی')),
                ('value', models.CharField(max_length=200, verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'شاخصه',
                'verbose_name_plural': 'مشخصات',
            },
        ),
    ]
